version: 2.1
orbs:
  node: circleci/node@5.0.3
workflows:
  test:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn
      - run:
        command: yarn build
      - run:
        command: yarn test
# VS Code Extension Version: 1.5.0
